// src/app/shared/nebular.module.ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  NbThemeModule,
  NbLayoutModule,
  NbDialogModule,
  NbToastrModule,
  NbMenuModule,
  NbUserModule,
  NbInputModule,
  NbButtonModule,
  NbPopoverModule,
  NbActionsModule,
  NbCardModule,
  NbIconModule,
  NbSearchModule,
  NbButtonGroupModule,
  NbListModule,
  NbContextMenuModule,
  NbBadgeModule,
  NbSpinnerModule,
  NbCheckboxModule,
  NbSelectModule,
  NbTooltipModule,
  NbAccordionModule,
  NbAlertModule,
  NbToggleModule,
  NbRadioModule,
} from '@nebular/theme';

import { NbEvaIconsModule } from '@nebular/eva-icons';

@NgModule({
  imports: [
    CommonModule,
    // Import Nebular modules WITHOUT forRoot here.
    // Root providers are configured in main.ts via bootstrapApplication.
    NbThemeModule,
    NbLayoutModule,
    NbDialogModule,
    NbToastrModule,
    NbMenuModule,
    NbUserModule,
    NbInputModule,
    NbButtonModule,
    NbPopoverModule,
    NbActionsModule,
    NbCardModule,
    NbIconModule,
    NbSearchModule,
    NbButtonGroupModule,
    NbListModule,
    NbContextMenuModule,
    NbEvaIconsModule,
    NbBadgeModule,
    NbSpinnerModule,
    NbToggleModule,
    NbCheckboxModule,
    NbSelectModule,
    NbTooltipModule,
    NbAccordionModule,
    NbAlertModule,
    NbRadioModule,
  ],
  exports: [
    CommonModule,
    NbThemeModule,
    NbLayoutModule,
    NbDialogModule,
    NbToastrModule,
    NbUserModule,
    NbInputModule,
    NbMenuModule,
    NbButtonModule,
    NbPopoverModule,
    NbActionsModule,
    NbCardModule,
    NbIconModule,
    NbSearchModule,
    NbButtonGroupModule,
    NbListModule,
    NbContextMenuModule,
    NbEvaIconsModule,
    NbBadgeModule,
    NbSpinnerModule,
    NbToggleModule,
    NbCheckboxModule,
    NbSelectModule,
    NbTooltipModule,
    NbAccordionModule,
    NbAlertModule,
    NbRadioModule,
  ]
})
export class NebularModule {}
