// src/app/shared/nebular.module.ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  NbThemeModule,
  NbLayoutModule,
  NbDialogModule,
  NbToastrModule,
  NbMenuModule,
  NbUserModule,
  NbInputModule,
  NbButtonModule,
  NbPopoverModule,
  NbActionsModule,
  NbCardModule,
  NbIconModule,
  NbSearchModule,
  NbButtonGroupModule,
  NbContextMenuModule,
  NbBadgeModule,
  NbSpinnerModule,
  NbToggleComponent,
  NbCheckboxModule,
  NbSelectModule,
  NbTooltipModule,
  NbAccordionModule,
  NbAlertModule,
  NbToggleModule,
} from '@nebular/theme';

import { NbEvaIconsModule } from '@nebular/eva-icons';

@NgModule({
  imports: [
    CommonModule,
    NbThemeModule.forRoot(),
    NbLayoutModule,
    NbDialogModule.forRoot(),
    NbToastrModule.forRoot(),
    NbMenuModule.forRoot(),
    NbUserModule,
    NbInputModule,
    NbButtonModule,
    NbPopoverModule,
    NbActionsModule,
    NbCardModule,
    NbIconModule,
    NbSearchModule,
    NbButtonGroupModule,
    NbContextMenuModule,
    NbEvaIconsModule,
    NbBadgeModule,
    NbSpinnerModule,
    NbToggleModule,
    NbCheckboxModule,
    NbSelectModule,
    NbTooltipModule,
    NbAccordionModule,
    NbAlertModule,
  ],
  exports: [
    CommonModule,
    NbThemeModule,
    NbLayoutModule,
    NbDialogModule,
    NbToastrModule,
    NbUserModule,
    NbInputModule,
    NbMenuModule,
    NbButtonModule,
    NbPopoverModule,
    NbActionsModule,
    NbCardModule,
    NbIconModule,
    NbSearchModule,
    NbButtonGroupModule,
    NbContextMenuModule,
    NbEvaIconsModule,
    NbBadgeModule,
    NbSpinnerModule,
    NbToggleModule,
    NbCheckboxModule,
    NbSelectModule,
    NbTooltipModule,
    NbAccordionModule,
    NbAlertModule,
  ]
})
export class NebularModule {}
